apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  namespace: wordpress
spec:
  accessModes:
   - ReadWriteMany
  mountOptions:
   - nfsvers=4.1
  capacity:
     storage: 8Gi
  nfs:
     server: 10.8.12.66
     path: "/mysql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc
  namespace: wordpress
spec:
  accessModes:
   - ReadWriteMany
  resources:
     requests:
       storage: 8Gi