apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
spec:
  accessModes:
   - ReadWriteMany
  mountOptions:
   - nfsvers=4.1
  capacity:
     storage: 8Gi
  nfs:
     server: 10.8.12.66
     path: "/mysql"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 8Gi